### ISSUE TITLE
Is reordering before executing each task efficient? 

### ISSUE THREAD

**Issue by andrewsokolov** [cmseaton42/task-easy#2]
Maybe heap will be more situated for that case then plain array?

**Comment by cmseaton42** [comment]
The initial thought process behind calling `_reorder` before running each tasks are as follows.

- we do not know how long each scheduled task will take to complete thus many additional tasks could be added during the execution of the active task thus requiring us to `_reorder` again to ensure any high priority tasks that may have been added during the current execution bubble up as appropriate.
- `_reorder` runs in O(n) time. For common use cases, the overhead associated running `_reorder` is negligible.
- this was done in the interest of keeping it simple in the short term


To answer your question though, no it not the most efficient way to do this. I think the following optimizations could be easily made to decrease overhead.
- add an `_insert` method that pushes a new item onto the array and then allows the item to swim up to an appropriate position within the array to satisfy the `max-heap` condition. This could be done in O(lgn) time.
- add a `_remove` method that takes the highest priority item off the top and re-establishes the `max-heap` property. This could also be done in O(lgn) time.

Did you have any other ways in mind to improve performance? 

Also, thanks for pointing this out.

**Comment by cmseaton42** [comment]
Closing, resolved with #3
